---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../common-functions
- ../application-deployment/store/quarkuscoffeeshop-majestic-monolith

resources:
  - pvc/pvc.yml
  - pvc/maven-source-pvc.yml
  - tektontasks/pushImageToQuay.yaml
  - tektontasks/pushImageToQuay-latest.yaml
  - resources/git-pipeline-resource.yaml
  - resources/image-pipeline-resource.yaml
  - pipeline/deploy-pipeline.yaml

