apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeoffice-ingress
  labels:
    app: homeoffice-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.ingress }}
  selector:
    matchLabels:
      app: homeoffice-ingress
  template:
    metadata:
      name: homeoffice-ingress-deployment
      labels:
        app: homeoffice-inggress
        release: {{ .Release.Name }}
        app.kubernetes.io/component: homeoffice-ingress
        app.kubernetes.io/instance: homeoffice-ingress
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: homeoffice-ingress
          image: {{ .Values.global.imageregistry.hostname }}/{{ .Values.global.imageregistry.account }}/quarkuscoffeeshop-barista:{{ .Values.global.homeofficeIngress.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
