---
apiVersion: v1
kind: Service
metadata:
  name: quarkuscoffeeshop-homeoffice-ui
  labels:
    app:  homeoffice-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app:  homeoffice-ui
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
