apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quarkuscoffeeshop-majestic-monolith-deployment.yaml
  - quarkuscoffeeshop-majestic-monolith-service.yaml
  - quarkuscoffeeshop-majestic-monolith-route.yaml
transformers:
- ./transformer-patches.yaml