apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-majestic-monolith-git
  labels:
    app: quarkuscoffeeshop-majestic-monolith
  namespace: quarkuscoffeeshop-cicd
spec:
  type: git
  params:
  - name: url
    value: https://github.com/jeremyrdavis/quarkuscoffeeshop-majestic-monolith
