---
global:
  hubClusterDomain: hub.example.com
  localClusterDomain: example.com

clusterGroup:
  isHubCluster: false

kafkaClusterName: cafe-cluster

mirrorMaker:
  enabled: true

  certSecretName: homeoffice-kafka-cluster-cluster-ca-cert

  localKafkaBootstrapHost: cafe-cluster-kafka-bootstrap
  localKafkaBootstrapPort: 9092

  #remoteKafkaBootstrapHost: homeoffice-cluster-kafka-tls-bootstrap-coffeeshop-homeoffice
  remoteKafkaBootstrapHost: homeoffice-cluster-kafka-bootstrap-coffeeshop-homeoffice

