apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quarkuscoffeeshop-integration
resources:
  - quarkuscoffeeshop-customermocker-deployment.yaml
  - quarkuscoffeeshop-customermocker-service.yaml
  - quarkuscoffeeshop-customermocker-route.yaml
transformers:
- ./transformer-patches.yaml