---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: quarkuscoffeeshop-cicd
  generateName: homeoffice-backend-
  labels:
    app: homeoffice-backend
    argocd.argoproj.io/instance: quarkuscoffeeshop-cicd
    tekton.dev/pipeline: build-and-push-homeoffice-backend
spec:
  pipelineRef:
    name: build-and-push-homeoffice-backend
  resources:
    - name: app-git
      resourceRef:
        name: homeoffice-backend-git
    - name: image
      resourceRef:
        name: homeoffice-backend-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: homeoffice-backend-shared-workspace-pvc
    - name: maven-settings
      persistentVolumeClaim:
        claimName: homeoffice-backend-maven-settings-pvc
