---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: quarkuscoffeeshop-cicd
  generateName: quarkuscoffeeshop-homeoffice-ui-
  labels:
    app: quarkuscoffeeshop-homeoffice-ui
    argocd.argoproj.io/instance: quarkuscoffeeshop-cicd
    tekton.dev/pipeline: build-and-push-quarkuscoffeeshop-homeoffice-ui
spec:
  pipelineRef:
    name: build-and-push-quarkuscoffeeshop-homeoffice-ui
  resources:
    - name: app-git
      resourceRef:
        name: quarkuscoffeeshop-homeoffice-ui-git
    - name: image
      resourceRef:
        name: quarkuscoffeeshop-homeoffice-ui-image
  serviceAccountName: pipeline
  taskRunSpecs:
    - pipelineTaskName: build-nodejsapp
      taskServiceAccountName: priv-pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: quarkuscoffeeshop-homeoffice-ui-shared-workspace-pvc
    - name: maven-settings
      persistentVolumeClaim:
        claimName: quarkuscoffeeshop-homeoffice-ui-maven-settings-pvc
