apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: homeoffice-ui-git
  labels:
    app: quarkuscoffeeshop-homeoffice-ui
spec:
  type: git
  params:
  - name: url
    value: https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-homeoffice-ui
