apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-git
  namespace: quarkuscoffeeshop-cicd
spec:
  type: git
  params:
    - name: url
      value: https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-homeoffice-ui.git
    - name: revision
      value: main
    - name: sslVerify
      value: "false"