---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: homeoffice-backend
    app.kubernetes.io/component: homeoffice-backend
    app.kubernetes.io/instance: homeoffice-backend
  name: homeoffice-backend
  namespace: quarkuscoffeeshop-homeoffice
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: homeoffice-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: homeoffice-backend
    spec:
      containers:
      - env:
        - name: KAFKA_BOOTSTRAP_URLS
          value: 'cafe-cluster-kafka-bootstrap:9092'
        - name: POSTGRESQL_JDBC_URL
          value: jdbc:postgresql://coffeeshopdb:5432/coffeeshopdb?currentSchema=coffeeshop
        - name: POSTGRESQL_USER
          value: coffeshopadmin
        - name: POSTGRESQL_PASSWORD
          value: CHANGEME
        image: image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/homeoffice-backend:latest
        imagePullPolicy: IfNotPresent
        name: homeoffice-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
